
/// The error type used by the `init(opaqueCode:)` initializer generated by the `@ErrorCode` macro.
public protocol OpaqueCodeInitializerError: Error {
    
    // MARK: - Static properties
    
    /// Thrown when the `opaqueCode` provided to the `init(opaqueCode:)` initializer is empty.
    static var opaqueCodeIsEmpty: Self { get }
    
    // MARK: - Static functions
    
    /// Thrown when the `opaqueCode` provided to the `init(opaqueCode:)` initializer does not match any of the static values in the associated `OpaqueValue` type.
    /// - Parameter code: The `opaqueCode` that was not successfully matched to an `OpaqueValue`.
    static func unrecognizedOpaqueCode(_ opaqueCode: String) -> Self
    
    /// Thrown when the the `init(opaqueCode:)` initializer reaches the bottom of a nested `ErrorCode` without using all of the components created when separating the full, top level code with \"-\".
    /// - Parameter components: The individual, unused components not used by the `init(opaqueCode:)` initializer. The number of components represents the expected remaining number of nesting levels.
    static func unusedOpaqueCodeComponents(_ components: [String]) -> Self
}
